name: Python Code Quality

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    environment: Staging
    env:
      APP_NAME: ${{ vars.APP_NAME }}
      ENVIRONMENT: ${{ vars.ENVIRONMENT }}
      APP_KEY: ${{ secrets.APP_KEY }}
      ALGORITHM: ${{ secrets.ALGORITHM }}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{ vars.ACCESS_TOKEN_EXPIRE_MINUTES }}
      MONGODB_URL: ${{ secrets.MONGODB_URL }}
      DB_NAME: ${{ vars.DB_NAME }}
      TEST_ENDPOINT: ${{ vars.TEST_ENDPOINT }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black flake8 isort mypy pytest autoflake

      # Remove unused imports first
      - name: Remove unused imports
        run: |
          autoflake --in-place --remove-all-unused-imports --recursive app/

      # Auto-format code with Black
      - name: Format code with Black
        run: |
          black app

      # Auto-sort imports with isort
      - name: Sort imports with isort
        run: |
          isort app

      # Now check if formatting is correct
      - name: Check formatting with Black
        run: |
          black --check app

      # Now check if imports are sorted correctly
      - name: Check import sorting with isort
        run: |
          isort --check-only app

      # Run flake8 with appropriate configuration
      - name: Lint with flake8
        run: |
          flake8 app --max-line-length=88 --extend-ignore=E203,F401,F811

      - name: Type check with mypy
        run: |
          mypy app

      - name: Test with pytest
        run: |
          pytest

      - name: Security audit
        run: |
          pip install safety
          safety check